services:
  - type: web
    name: nl2sql-api
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/data
    headers:
      - path: /
        name: Access-Control-Allow-Origin
        value: "*"
